// Code generated by internal/cmd/schemagen. DO NOT EDIT.
//
// Source: schema/meta.json, version 1, cross-checked against the x-method and
// x-side annotations in schema/schema.json.

package acp

// The wire names of the methods the specification defines. Unexported because a
// caller names a method by calling the operation for it: the method strings, the
// request identifiers and the envelope are all plumbing, and a caller who has to
// know them has been handed the plumbing.
const (
	methodCancelRequest            = "$/cancel_request"
	methodAuthenticate             = "authenticate"
	methodDocumentDidChange        = "document/didChange"
	methodDocumentDidClose         = "document/didClose"
	methodDocumentDidFocus         = "document/didFocus"
	methodDocumentDidOpen          = "document/didOpen"
	methodDocumentDidSave          = "document/didSave"
	methodElicitationComplete      = "elicitation/complete"
	methodElicitationCreate        = "elicitation/create"
	methodFsReadTextFile           = "fs/read_text_file"
	methodFsWriteTextFile          = "fs/write_text_file"
	methodInitialize               = "initialize"
	methodLogout                   = "logout"
	methodMcpConnect               = "mcp/connect"
	methodMcpDisconnect            = "mcp/disconnect"
	methodMcpMessage               = "mcp/message"
	methodNesAccept                = "nes/accept"
	methodNesClose                 = "nes/close"
	methodNesReject                = "nes/reject"
	methodNesStart                 = "nes/start"
	methodNesSuggest               = "nes/suggest"
	methodProvidersDisable         = "providers/disable"
	methodProvidersList            = "providers/list"
	methodProvidersSet             = "providers/set"
	methodSessionCancel            = "session/cancel"
	methodSessionClose             = "session/close"
	methodSessionDelete            = "session/delete"
	methodSessionFork              = "session/fork"
	methodSessionList              = "session/list"
	methodSessionLoad              = "session/load"
	methodSessionNew               = "session/new"
	methodSessionPrompt            = "session/prompt"
	methodSessionRequestPermission = "session/request_permission"
	methodSessionResume            = "session/resume"
	methodSessionSetConfigOption   = "session/set_config_option"
	methodSessionSetMode           = "session/set_mode"
	methodSessionUpdate            = "session/update"
	methodTerminalCreate           = "terminal/create"
	methodTerminalKill             = "terminal/kill"
	methodTerminalOutput           = "terminal/output"
	methodTerminalRelease          = "terminal/release"
	methodTerminalWaitForExit      = "terminal/wait_for_exit"
)

// A methodSide is which peer serves a method. Both directions carry requests:
// fourteen of the specification's methods run from the agent to the client, so
// this is not a client library with a server mode bolted on.
type methodSide uint8

const (
	// sideAgent is served by the agent, so a client sends it.
	sideAgent methodSide = iota
	// sideClient is served by the client, so an agent sends it.
	sideClient
	// sideBoth may be sent by either peer.
	sideBoth
	// sideProtocol belongs to the connection rather than to either peer.
	sideProtocol
)

// A methodShape is whether a method expects a response. The schema does not say
// so directly; it follows from which payloads it defines for the method.
type methodShape uint8

const (
	// shapeRequest expects a response.
	shapeRequest methodShape = iota
	// shapeNotification has none.
	shapeNotification
	// shapeEither is defined both ways, which mcp/message is.
	shapeEither
)

type methodDescriptor struct {
	side  methodSide
	shape methodShape
}

// standardMethods is every method the specification defines, and the set the
// extension API reserves.
//
// An unrestricted method string on Call and Notify would be a hole through every
// invariant this package has: a caller could pass session/prompt and bypass the
// generated params type, the outbound validation, the session-ID binding and the
// capability gate. A standard method has exactly one path through the typed codec,
// and this is what says which names those are.
var standardMethods = map[string]methodDescriptor{
	methodCancelRequest:            {sideProtocol, shapeNotification},
	methodAuthenticate:             {sideAgent, shapeRequest},
	methodDocumentDidChange:        {sideAgent, shapeNotification},
	methodDocumentDidClose:         {sideAgent, shapeNotification},
	methodDocumentDidFocus:         {sideAgent, shapeNotification},
	methodDocumentDidOpen:          {sideAgent, shapeNotification},
	methodDocumentDidSave:          {sideAgent, shapeNotification},
	methodElicitationComplete:      {sideClient, shapeNotification},
	methodElicitationCreate:        {sideClient, shapeRequest},
	methodFsReadTextFile:           {sideClient, shapeRequest},
	methodFsWriteTextFile:          {sideClient, shapeRequest},
	methodInitialize:               {sideAgent, shapeRequest},
	methodLogout:                   {sideAgent, shapeRequest},
	methodMcpConnect:               {sideClient, shapeRequest},
	methodMcpDisconnect:            {sideClient, shapeRequest},
	methodMcpMessage:               {sideBoth, shapeEither},
	methodNesAccept:                {sideAgent, shapeNotification},
	methodNesClose:                 {sideAgent, shapeRequest},
	methodNesReject:                {sideAgent, shapeNotification},
	methodNesStart:                 {sideAgent, shapeRequest},
	methodNesSuggest:               {sideAgent, shapeRequest},
	methodProvidersDisable:         {sideAgent, shapeRequest},
	methodProvidersList:            {sideAgent, shapeRequest},
	methodProvidersSet:             {sideAgent, shapeRequest},
	methodSessionCancel:            {sideAgent, shapeNotification},
	methodSessionClose:             {sideAgent, shapeRequest},
	methodSessionDelete:            {sideAgent, shapeRequest},
	methodSessionFork:              {sideAgent, shapeRequest},
	methodSessionList:              {sideAgent, shapeRequest},
	methodSessionLoad:              {sideAgent, shapeRequest},
	methodSessionNew:               {sideAgent, shapeRequest},
	methodSessionPrompt:            {sideAgent, shapeRequest},
	methodSessionRequestPermission: {sideClient, shapeRequest},
	methodSessionResume:            {sideAgent, shapeRequest},
	methodSessionSetConfigOption:   {sideAgent, shapeRequest},
	methodSessionSetMode:           {sideAgent, shapeRequest},
	methodSessionUpdate:            {sideClient, shapeNotification},
	methodTerminalCreate:           {sideClient, shapeRequest},
	methodTerminalKill:             {sideClient, shapeRequest},
	methodTerminalOutput:           {sideClient, shapeRequest},
	methodTerminalRelease:          {sideClient, shapeRequest},
	methodTerminalWaitForExit:      {sideClient, shapeRequest},
}

// isStandardMethod reports whether the specification defines name, which is what
// the extension API refuses and what a fallback handler is not offered.
func isStandardMethod(name string) bool {
	_, standard := standardMethods[name]
	return standard
}
